apiVersion: v1
data:
  dhcpd.conf: |
    option domain-name-servers 8.8.8.8, 8.8.4.4;
    option subnet-mask 255.255.255.0;
    option routers 10.10.0.1;
    subnet 10.10.0.0 netmask 255.255.255.0 {
      range 10.10.0.100 10.10.0.199;
    }
kind: ConfigMap
metadata:
  name: dhcpd-conf
  namespace: kube-pxe-system
