apiVersion: v1
data:
  dnsmasq.conf: |
    port=0
    dhcp-range=10.10.0.100,10.10.0.149,255.255.255.0,2h
    dhcp-option = option:router, 10.10.0.1
    dhcp-option = option:dns-server, 8.8.8.8
    log-dhcp
    enable-tftp
    tftp-root=/tftpboot
    pxe-service=0,"Raspberry Pi Boot"

kind: ConfigMap
metadata:
  name: dnsmasq-conf
  namespace: kube-pxe-system
