apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  namespace: kube-pxe-system
  labels:
    app: dnsmasq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnsmasq
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      hostNetwork: true
      containers:
      - image: andyshinn/dnsmasq
        args:
          - --log-facility=-
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        imagePullPolicy: Always
        name: dnsmasq
        volumeMounts:
        - mountPath: /tftpboot
          name: tftpboot
        - mountPath: /etc/dnsmasq.conf
          name: dnsmasq-conf
          subPath: dnsmasq.conf
      volumes:
      - name: tank
        hostPath:
          path: /tank/pv/dnsmasq
          type: ""
      - name: tftpboot
        hostPath:
          path: /tank/pv/tftpboot
          type: ""
      - name: dnsmasq-conf
        configMap:
          name: dnsmasq-conf
