apiVersion: v1
data:
  dnsmasq.conf: |
    port=0
    bind-dynamic
    dhcp-range=10.10.0.1,proxy
    log-dhcp
    enable-tftp
    tftp-root=/tftpboot
    pxe-service=0,"Raspberry Pi Boot"

kind: ConfigMap
metadata:
  name: dnsmasq-conf
  namespace: kube-pxe-system
